# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
trigger:
- main

jobs:
- job:
  pool:
    vmImage: 'ubuntu-18.04'
  timeoutInMinutes: 0

  steps:
  # https://docs.microsoft.com/azure/devops/pipelines/languages/python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
    displayName: 'Use Python 3.6'

  - task: Cache@2
    inputs:
      key: 'poetry | "$(Agent.OS)" | poetry.lock'
      # This is hard-coded but I can't find the right variable for it,
      # and ~ doesn't work.
      path: /home/vsts/.cache/pypoetry/virtualenvs
    displayName: 'Cache Python packages'

  - script: |
      # NOTE: Microsoft SQL Tools are already installed on this image.
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      sudo apt-get update
      sudo apt-get install exuberant-ctags
    displayName: 'Install system dependencies'

  - script: |
      source $HOME/.poetry/env
      poetry install
    displayName: 'Install Python packages'

  - script: |
      source $HOME/.poetry/env
      poetry export --dev --format requirements.txt --output requirements.txt
    displayName: 'Export dependencies for Component Governance Detection'

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    inputs:
      failOnAlert: true
    displayName: 'Microsoft Internal Open Source Component Governance Detection'

  - script: |
      source $HOME/.poetry/env
      poetry run flake8
    displayName: 'Semantics check with flake8'

  - script: |
      source $HOME/.poetry/env
      poetry run isort --check-only
    displayName: 'Import check with isort'

  - script: |
      source $HOME/.poetry/env
      poetry run black --check .
    displayName: 'Formatting check with black'

  - script: |
      source $HOME/.poetry/env
      poetry run ./CommA.py --dry-run --since '6 months ago' --verbose add-distro --name 'Ubuntu18.04' --url 'https://git.launchpad.net/~canonical-kernel/ubuntu/+source/linux-azure/+git/bionic' --revision 'Ubuntu-azure-5.0.0-1036.38'
    displayName: 'CommA: Add single downstream distro'

  - script: |
      source $HOME/.poetry/env
      poetry run ./CommA.py --dry-run --since '6 months ago' --verbose run --upstream
    displayName: 'CommA: Monitor Upstream'

  - script: |
      source $HOME/.poetry/env
      poetry run ./CommA.py --dry-run --since '6 months ago' --verbose run --downstream
    displayName: 'CommA: Monitor Downstream'

  - script: |
      source $HOME/.poetry/env
      touch symbols.txt
      poetry run ./CommA.py --dry-run --no-fetch --verbose print-symbols
    displayName: 'CommA: Print Missing Symbols'
