[project]
name = "CommA"
version = "0.1.0"
description = "Linux Commit Analyzer"
python = "^3.7"

[dependencies]
pygit2 = "^1.0"
elasticsearch-dsl = "^7.1"

[dev-dependencies]
flake8 = "^3.7"
black = "^19.10"

[tool.black]
